import os

MODEL_DIR = "./models"
XGBOOST_MODEL_FILENAME = "xgboost_sentiment_classifier.pkl"
LABEL_ENCODER_FILENAME = "label_encoder.pkl"
MODEL_PERFORMANCE_FILENAME = "model_performance.json"

XGBOOST_MODEL_PATH = os.path.join(MODEL_DIR, XGBOOST_MODEL_FILENAME)
LABEL_ENCODER_PATH = os.path.join(MODEL_DIR, LABEL_ENCODER_FILENAME)
MODEL_PERFORMANCE_PATH = os.path.join(MODEL_DIR, MODEL_PERFORMANCE_FILENAME)
EMBEDDING_MODEL_NAME = 'all-MiniLM-L6-v2'
